<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="2041" started-at="2022-08-02T20:26:19 IST" finished-at="2022-08-02T20:26:21 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="2041" started-at="2022-08-02T20:26:19 IST" finished-at="2022-08-02T20:26:21 IST">
      <class name="com.TestNgF.TimeOut_InvocationCount">
        <test-method status="PASS" signature="loop()[pri:0, instance:com.TestNgF.TimeOut_InvocationCount@7d0587f1]" name="loop" duration-ms="5" started-at="2022-08-02T20:26:19 IST" finished-at="2022-08-02T20:26:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loop -->
        <test-method status="PASS" signature="loop()[pri:0, instance:com.TestNgF.TimeOut_InvocationCount@7d0587f1]" name="loop" duration-ms="1" started-at="2022-08-02T20:26:19 IST" finished-at="2022-08-02T20:26:19 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loop -->
        <test-method status="FAIL" signature="timeup()[pri:0, instance:com.TestNgF.TimeOut_InvocationCount@7d0587f1]" name="timeup" duration-ms="2010" started-at="2022-08-02T20:26:19 IST" finished-at="2022-08-02T20:26:21 IST">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method com.TestNgF.TimeOut_InvocationCount.timeup() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestNgF.TimeOut_InvocationCount.timeup() didn't finish within the time-out 2000
at org.testng.internal.MethodInvocationHelper.invokeWithTimeoutWithNewExecutor(MethodInvocationHelper.java:384)
at org.testng.internal.MethodInvocationHelper.invokeWithTimeout(MethodInvocationHelper.java:283)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:604)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- timeup -->
      </class> <!-- com.TestNgF.TimeOut_InvocationCount -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
